title: Dockmaster Documentation
output: docs/
exclude:
  - spec/
  - lib/theme_template/
theme: default

# Theme settings
site_logo: /logo/dockmaster-logo-horizontal.svg
source_repo: https://github.com/chrisblutz/dockmaster
doc_home: Dockmaster
