Metrics/AbcSize:
  Enabled: False
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/dockmaster/docs/processor_defaults_spec.rb'
    - 'spec/dockmaster/output/output_spec.rb'
    - 'spec/dockmaster/output/erb/base_helper_spec.rb'
    - 'spec/dockmaster/parser/doc_parser_spec.rb'
    - 'spec/dockmaster/parser/store_spec.rb'
    - 'spec/dockmaster/plugin_spec.rb'
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false
  Max: 30
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
EndOfLine:
  Enabled: false
