Metrics/AbcSize:
  Enabled: False
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/dockmaster/output/erb/base_helper_spec.rb'
    - 'spec/dockmaster/parser/doc_parser_spec.rb'
    - 'spec/dockmaster/parser/store_spec.rb'
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false
  Max: 20
Metrics/PerceivedComplexity:
  Max: 8
EndOfLine:
  Enabled: false
