AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'Rakefile'
Metrics/AbcSize:
  Enabled: False
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false
  Max: 30
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
EndOfLine:
  Enabled: false
