language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--debug --2.0"
cache: bundler
before_script: bundle update
script:
  - bundle exec rspec
  - bundle exec rubocop
